[build-system]
requires = [
    "setuptools<=43",    
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scikit-learn",
    "jupyter",
    "scipy",
    "joblib",
]
build-backend = "setuptools.build_meta"