[build-system]
requires = [
    "setuptools>=42",
    "numpy",
    "pandas",
    "matplotlib",
    "scikit-learn",
    "jupyter",
    "scipy",
    "joblib",
    
]
build-backend = "setuptools.build_meta"